CREATE TABLE LAS_CONTRACT_OPPOSITE_QUALITY 
(
  ID NUMBER(19) NOT NULL 
, ZZMC VARCHAR2(200) 
, ZZSM VARCHAR2(200) 
, ZZYXQ VARCHAR2(60) 
, OPPOSITEID VARCHAR2(60) 
, CONSTRAINT LAS_CONTRACT_OPPOSITE_QUALITY_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LAS_CONTRACT_OPPOSITE_QUALITY ON LAS_CONTRACT_OPPOSITE_QUALITY (ID ASC) 
  )
  ENABLE 
)